//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace project.ModelDO
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class projectContextEntities : DbContext
    {
        public projectContextEntities()
            : base("name=projectContextEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ProfileRoleUser_Result> ProfileRoleUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfileRoleUser_Result>("ProfileRoleUser");
        }
    }
}
