//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronic_store.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class electronic_sotore_Entities : DbContext
    {
        public electronic_sotore_Entities()
            : base("name=electronic_sotore_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ProfileRoleUser_Result> ProfileRoleUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfileRoleUser_Result>("ProfileRoleUser");
        }
    
        public virtual ObjectResult<viewAccesorios_Result> viewAccesorios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewAccesorios_Result>("viewAccesorios");
        }
    
        public virtual ObjectResult<viewCase_Result> viewCase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewCase_Result>("viewCase");
        }
    
        public virtual ObjectResult<viewDetailsProducto_Result> viewDetailsProducto(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDetailsProducto_Result>("viewDetailsProducto", iDParameter);
        }
    
        public virtual ObjectResult<viewDiscoDuro_Result> viewDiscoDuro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDiscoDuro_Result>("viewDiscoDuro");
        }
    
        public virtual ObjectResult<viewFuentePoder_Result> viewFuentePoder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewFuentePoder_Result>("viewFuentePoder");
        }
    
        public virtual ObjectResult<viewMonitor_Result> viewMonitor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewMonitor_Result>("viewMonitor");
        }
    
        public virtual ObjectResult<viewPerifericos_Result> viewPerifericos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewPerifericos_Result>("viewPerifericos");
        }
    
        public virtual ObjectResult<viewProcesador_Result> viewProcesador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProcesador_Result>("viewProcesador");
        }
    
        public virtual ObjectResult<viewProcesadorAMD_Result> viewProcesadorAMD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProcesadorAMD_Result>("viewProcesadorAMD");
        }
    
        public virtual ObjectResult<viewProcesadorIntel_Result> viewProcesadorIntel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProcesadorIntel_Result>("viewProcesadorIntel");
        }
    
        public virtual ObjectResult<viewRam_Result> viewRam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewRam_Result>("viewRam");
        }
    
        public virtual ObjectResult<viewTarjetaMadre_Result> viewTarjetaMadre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadre_Result>("viewTarjetaMadre");
        }
    
        public virtual ObjectResult<viewTarjetaVideo_Result> viewTarjetaVideo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideo_Result>("viewTarjetaVideo");
        }
    
        public virtual ObjectResult<viewDetailsProductos_Result> viewDetailsProductos(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDetailsProductos_Result>("viewDetailsProductos", iDParameter);
        }
    
        public virtual ObjectResult<viewWishlistUser_Result> viewWishlistUser(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewWishlistUser_Result>("viewWishlistUser", userNameParameter);
        }
    
        public virtual ObjectResult<viewDetailsInvoice_Result> viewDetailsInvoice(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDetailsInvoice_Result>("viewDetailsInvoice", iDParameter);
        }
    
        public virtual ObjectResult<ReportSales_Result> ReportSales(Nullable<System.DateTime> dateInitial, Nullable<System.DateTime> dateFinal)
        {
            var dateInitialParameter = dateInitial.HasValue ?
                new ObjectParameter("dateInitial", dateInitial) :
                new ObjectParameter("dateInitial", typeof(System.DateTime));
    
            var dateFinalParameter = dateFinal.HasValue ?
                new ObjectParameter("dateFinal", dateFinal) :
                new ObjectParameter("dateFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportSales_Result>("ReportSales", dateInitialParameter, dateFinalParameter);
        }
    
        public virtual ObjectResult<viewRam16GB_Result> viewRam16GB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewRam16GB_Result>("viewRam16GB");
        }
    
        public virtual ObjectResult<viewRam8GB_Result> viewRam8GB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewRam8GB_Result>("viewRam8GB");
        }
    
        public virtual ObjectResult<viewTarjetaMadreAMD_Result> viewTarjetaMadreAMD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadreAMD_Result>("viewTarjetaMadreAMD");
        }
    
        public virtual ObjectResult<viewTarjetaMadreAsus_Result> viewTarjetaMadreAsus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadreAsus_Result>("viewTarjetaMadreAsus");
        }
    
        public virtual ObjectResult<viewTarjetaMadreGigabyte_Result> viewTarjetaMadreGigabyte()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadreGigabyte_Result>("viewTarjetaMadreGigabyte");
        }
    
        public virtual ObjectResult<viewTarjetaMadreIntel_Result> viewTarjetaMadreIntel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadreIntel_Result>("viewTarjetaMadreIntel");
        }
    
        public virtual ObjectResult<viewTarjetaMadreMSI_Result> viewTarjetaMadreMSI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadreMSI_Result>("viewTarjetaMadreMSI");
        }
    
        public virtual ObjectResult<viewTarjetaVideo2GB_Result> viewTarjetaVideo2GB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideo2GB_Result>("viewTarjetaVideo2GB");
        }
    
        public virtual ObjectResult<viewTarjetaVideo3GB_Result> viewTarjetaVideo3GB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideo3GB_Result>("viewTarjetaVideo3GB");
        }
    
        public virtual ObjectResult<viewTarjetaVideo4GB_Result> viewTarjetaVideo4GB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideo4GB_Result>("viewTarjetaVideo4GB");
        }
    
        public virtual ObjectResult<viewTarjetaVideo8GB_Result> viewTarjetaVideo8GB()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideo8GB_Result>("viewTarjetaVideo8GB");
        }
    
        public virtual ObjectResult<viewTarjetaVideoAsus_Result> viewTarjetaVideoAsus()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideoAsus_Result>("viewTarjetaVideoAsus");
        }
    
        public virtual ObjectResult<viewTarjetaVideoMSI_Result> viewTarjetaVideoMSI()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideoMSI_Result>("viewTarjetaVideoMSI");
        }
    
        public virtual ObjectResult<viewTarjetaVideoZotac_Result> viewTarjetaVideoZotac()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideoZotac_Result>("viewTarjetaVideoZotac");
        }
    
        public virtual ObjectResult<viewAccesoriosVentilador_Result> viewAccesoriosVentilador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewAccesoriosVentilador_Result>("viewAccesoriosVentilador");
        }
    
        public virtual ObjectResult<viewPerifericosCooler_Result> viewPerifericosCooler()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewPerifericosCooler_Result>("viewPerifericosCooler");
        }
    
        public virtual ObjectResult<viewPerifericosEnfriamientoLiquido_Result> viewPerifericosEnfriamientoLiquido()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewPerifericosEnfriamientoLiquido_Result>("viewPerifericosEnfriamientoLiquido");
        }
    
        public virtual ObjectResult<viewPerifericosTeclado_Result> viewPerifericosTeclado()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewPerifericosTeclado_Result>("viewPerifericosTeclado");
        }
    
        public virtual ObjectResult<GamingAMD_Result> GamingAMD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GamingAMD_Result>("GamingAMD");
        }
    
        public virtual ObjectResult<GamingIntel_Result> GamingIntel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<GamingIntel_Result>("GamingIntel");
        }
    
        public virtual ObjectResult<OfficeAMD_Result> OfficeAMD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OfficeAMD_Result>("OfficeAMD");
        }
    
        public virtual ObjectResult<OfficeIntel_Result> OfficeIntel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<OfficeIntel_Result>("OfficeIntel");
        }
    
        public virtual ObjectResult<viewDesktop_Result> viewDesktop()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDesktop_Result>("viewDesktop");
        }
    }
}
