//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace electronic_store.DataModel
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class electronic_sotore_Entities : DbContext
    {
        public electronic_sotore_Entities()
            : base("name=electronic_sotore_Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
    
        public virtual ObjectResult<ProfileRoleUser_Result> ProfileRoleUser()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ProfileRoleUser_Result>("ProfileRoleUser");
        }
    
        public virtual ObjectResult<viewAccesorios_Result> viewAccesorios()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewAccesorios_Result>("viewAccesorios");
        }
    
        public virtual ObjectResult<viewCase_Result> viewCase()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewCase_Result>("viewCase");
        }
    
        public virtual ObjectResult<viewDetailsProducto_Result> viewDetailsProducto(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDetailsProducto_Result>("viewDetailsProducto", iDParameter);
        }
    
        public virtual ObjectResult<viewDiscoDuro_Result> viewDiscoDuro()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDiscoDuro_Result>("viewDiscoDuro");
        }
    
        public virtual ObjectResult<viewFuentePoder_Result> viewFuentePoder()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewFuentePoder_Result>("viewFuentePoder");
        }
    
        public virtual ObjectResult<viewMonitor_Result> viewMonitor()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewMonitor_Result>("viewMonitor");
        }
    
        public virtual ObjectResult<viewPerifericos_Result> viewPerifericos()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewPerifericos_Result>("viewPerifericos");
        }
    
        public virtual ObjectResult<viewProcesador_Result> viewProcesador()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProcesador_Result>("viewProcesador");
        }
    
        public virtual ObjectResult<viewProcesadorAMD_Result> viewProcesadorAMD()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProcesadorAMD_Result>("viewProcesadorAMD");
        }
    
        public virtual ObjectResult<viewProcesadorIntel_Result> viewProcesadorIntel()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewProcesadorIntel_Result>("viewProcesadorIntel");
        }
    
        public virtual ObjectResult<viewRam_Result> viewRam()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewRam_Result>("viewRam");
        }
    
        public virtual ObjectResult<viewTarjetaMadre_Result> viewTarjetaMadre()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaMadre_Result>("viewTarjetaMadre");
        }
    
        public virtual ObjectResult<viewTarjetaVideo_Result> viewTarjetaVideo()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewTarjetaVideo_Result>("viewTarjetaVideo");
        }
    
        public virtual ObjectResult<viewDetailsProductos_Result> viewDetailsProductos(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDetailsProductos_Result>("viewDetailsProductos", iDParameter);
        }
    
        public virtual ObjectResult<viewWishlistUser_Result> viewWishlistUser(string userName)
        {
            var userNameParameter = userName != null ?
                new ObjectParameter("UserName", userName) :
                new ObjectParameter("UserName", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewWishlistUser_Result>("viewWishlistUser", userNameParameter);
        }
    
        public virtual ObjectResult<viewDetailsInvoice_Result> viewDetailsInvoice(Nullable<int> iD)
        {
            var iDParameter = iD.HasValue ?
                new ObjectParameter("ID", iD) :
                new ObjectParameter("ID", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<viewDetailsInvoice_Result>("viewDetailsInvoice", iDParameter);
        }
    
        public virtual ObjectResult<ReportSales_Result> ReportSales(Nullable<System.DateTime> dateInitial, Nullable<System.DateTime> dateFinal)
        {
            var dateInitialParameter = dateInitial.HasValue ?
                new ObjectParameter("dateInitial", dateInitial) :
                new ObjectParameter("dateInitial", typeof(System.DateTime));
    
            var dateFinalParameter = dateFinal.HasValue ?
                new ObjectParameter("dateFinal", dateFinal) :
                new ObjectParameter("dateFinal", typeof(System.DateTime));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<ReportSales_Result>("ReportSales", dateInitialParameter, dateFinalParameter);
        }
    }
}
